### ISSUE TITLE
ProdigyX/ProdigyPNP

### ISSUE THREAD

**Issue by WimpyJake** [ProdigyAPI/ProdigyX#199]
Which hack was made first? ProdigyX or ProdigyPNP?

**Comment by hostedposted** [comment]
ProdigyPNP was made first. Why?

**Comment by afkvido** [comment]
@WimpyJake 

@Prodigy-Hacking was the first organization to own the first Prodigy hack, called "Will's cheat menu", "PHEx", "PMGH", and "Prodigy Hacking". It's founder was @PatheticMustan

@ProdigyPNP forked Prodigy-Hacking when Prodigy-Hacking closed down, and made the "ProdigyPNP" hack. It's founder was @afkvido, along with donaldli and Eris.

**[ProdigyX](https://github.com/ProdigyAPI/ProdigyX)** was made shortly after ProdigyPNP was up and running stable. It's founder was @hostedposted, along with AGR.

Currently, Prodigy-Hacking is EOL and ProdigyPNP is down. ProdigyX is the only working hack for Prodigy, currently.

**Comment by WimpyJake** [comment]
wait I thought you guys nuked ProdigyPNP-

**Comment by afkvido** [comment]
They once gave us code which included hidden functionality (resets account unconsentually) affecting our users, but otherwise, no, they didn't nuke anyone.

We did a few times receive DDoS attacks, however it is unknown whether they came from ProdigyX or Prodigy Math.
